name: Build

on:
  # Trigger the workflow on push or pull request.
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew --no-daemon clean assembleDebug testDebug
     
    - name: Upload debug apk
      uses: actions/upload-artifact@v3
      with:
        name: apk-debug
        path: app/build/outputs/apk/debug/app-debug.apk
